# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_prize_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='img',
            field=models.FileField(upload_to='prize_image/'),
        ),
    ]
